parameters:
#    dota2_hero.example.class: Dota2\HeroBundle\Example

services:
#    dota2_hero.example:
#        class: %dota2_hero.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
