<?php

namespace Dota2\HeroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Dota2HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dota2HeroRepository extends EntityRepository
{
}
